version: "3"
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    restart: unless-stopped
    env_file: .env

    environment:
      - TOKEN=${TELEGRAM_TOKEN}

  vosk:
    image: "plyushchenko/vosk:latest"
    restart: always
    ports:
      - 2700:2700