version: "3"


services:
  db:
    container_name: "mongo-db"
    image: mongo:6.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/data/db/
    ports:
      - "127.0.0.1:27018:27017"

  bot:
    container_name: "bot"
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db

  silero-tts-service:
    image: "navatusein/silero-tts-service:1.0.0"
    container_name: "silero-tts-service"
    restart: unless-stopped
    env_file: .env

  whisper-asr-webservice:
    image: "onerahmet/openai-whisper-asr-webservice:v1.2.0"
    container_name: "whisper-asr-webservice"
    restart: unless-stopped
    env_file: .env

volumes:
  db-data:
