version: "3"


services:
  db:
    image: mongo:6.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/data/db/
    ports:
      - "127.0.0.1:27018:27017"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
      - kafka

  silero-tts-service:
    image: "navatusein/silero-tts-service:1.0.0"
    container_name: "silero-tts-service"
    restart: unless-stopped
    env_file: .env

  whisper-asr-webservice:
    image: "onerahmet/openai-whisper-asr-webservice:v1.2.0"
    container_name: "whisper-asr-webservice"
    restart: unless-stopped
    env_file: .env

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db-data:
