version: "3"


services:
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/data/db/
    ports:
      - "127.0.0.1:27018:27017"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db

volumes:
  db-data:
