version: "3"


services:
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    restart: unless-stopped
    env_file: .env
    volumes:
    - ./db/:/var/lib/mongodb/
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - TOKEN=${TELEGRAM_TOKEN}
      - MONGODB_PORT=${MONGO_PORT}

#  scheldule:
#    build:
#      context: .
#      dockerfile: DockerfileScheldule
#    image: scheldule
#    restart: unless-stopped
#    env_file: .env
#    depends_on:
#      - db
#    environment:
#      - MONGODB_HOST=db
#      - MONGODB_PASSWORD=${MONGO_PASSWORD}
#      - MONGODB_USERNAME=${MONGO_USERNAME}
#      - TOKEN=${TELEGRAM_TOKEN}
  #volumes:
  #dbdata:
  #