name: Container collection check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create .env
        env:
          TELEGRAM_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
        run: |
          cp env_file .env
          sed -i -e "s/PasteYourTelegramToken/${TELEGRAM_TOKEN}/g" .env

      - name: Build images
        run: |
          docker compose build

      - name: Pull images
        run: |
          docker compose pull --ignore-buildable

      - name: Start containers
        run: |
          docker compose up -d
          sleep 30

      - name: Check containers
        run: |
          echo "Some checks needed"