name: Checking requirements

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installation of Pipreqs
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
    - name: Dependency check (Run Pipreqs)
      run: |
        pipreqs --savepath src/reqs-check.txt --mode no-pin src/
        python requirements_check.py src/requirements.txt src/reqs-check.txt